name: userpforile check secrets

on:
  push:
    branches:
      - main
    paths:
      - "apis/userprofile/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  buildtest:
    name: Cehck secrets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [go, javascripts]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
