name: "Deploy"

on:
  push:
    branches:
      - main
    paths:
      - "iac/terraform/**"
      - ".github/workflows/**"

jobs:
  sample:
    runs-on: utuntu-latest
    outputs:
      RESOURCES_PREFIX: ${{ steps.resources_prefix.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get repo name
        uses: actions/github-script@v5
        id: resources_prefix
        with:
          result-encoding: string
          script: return context.repo.repo.toLowerCase()

      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      - name: Lint Terraform
        run: |
          terraform fmt -check

      - name: Validate configurations
        env:
          LOCATION: ${{ secrets.LOCATION }}
          RESOURCES_PREFIX: ${{ steps.resources_prefix.outputs.result }}
        run: |
          if [ ${#LOCATION} -eq 0 ]; then
              _error "Required LOCATION parameter is not set!"
              exit 1
          fi

          if [ ${#RESOURCES_PREFIX} -eq 0 ]; then
              _error "Required RESOURCES_PREFIX parameter is not set!"
              exit 1
          fi
