name: "userpforile build&test"

on:
  pull_request:
    branches:
      - main
    paths:
      - "apis/userprofile/**"
      - ".github/workflows/**"
  push:
    branches:
      - main
    paths:
      - "apis/userprofile/**"
      - ".github/workflows/**"

env:
  WORKING_DIRECTORY: "apis/userprofile"

defaults:
  run:
    shell: bash
    working-directory: "apis/userprofile"

jobs:
  buildtest:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      # Initialize, execute test
      - name: npm init
        run: npm ci
      - name: npm test
        run: npm run test

      # Report test results
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: ${{ env.WORKING_DIRECTORY }}/reports/*.xml