name: userpforile check secrets

on:
  push:
    branches:
      - main
    paths:
      - "apis/userprofile/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  buildtest:
    name: Cehck secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

     # Installs secret scanner on the runner
     - name: Install Whispers
       run: sudo pip install whispers
 
     # Scan repo for secrets
     - name: Run scanner for the repository
       run: whispers ${{ github.workspace }} > scan_output.json
 
     # Upload Artifacts
     - name: Upload the scan output
       uses: actions/upload-artifact@v2
       with:
         name: scan_results
         path: scan_output.json
         retention-days: 1
