name: userpforile check secrets

on:
  push:
    branches:
      - main
    paths:
      - "apis/userprofile/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  buildtest:
    name: Cehck secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Install gitguardian
        run: |
          apt update
          apt install python3-pip
          pip install -U ggshield

      - name: Scan secrets
        run: |
          ggshield secret scan -v --all-policies path ${{ github.workspace }}